### ISSUE TITLE
yarn install warning

### ISSUE THREAD

**Issue by dasa** [Esri/arcgis-html-sanitizer#23]
I get this warning when installing from `master`:

> warning " > ts-jest@24.0.0" has incorrect peer dependency "jest@>=24 <25".

**Comment by dasa** [comment]
I think `jest` needs to be updated to 24.x.

**Comment by ssylvia** [comment]
Fix in this commit: https://github.com/Esri/arcgis-html-sanitizer/commit/76ab51dc11ec8f0dab60d66b362b5829df9b7a1a
