### ISSUE TITLE
White List Update Request

### ISSUE THREAD

**Issue by YukiDayDreamer** [Esri/arcgis-html-sanitizer#28]
I noticed the white list attributes of `div` tag is slightly different from the one in [ArcGIS Online](https://doc.arcgis.com/en/arcgis-online/reference/supported-html.htm), which should be `[style, align]`.

Would you consider to update this?

Thanks.

**Comment by bsvensson** [comment]
@BlakeStearman - which is correct from ArcGIS Online perspective? (I'm assuming the doc, but want to doublecheck)...

**Comment by BlakeStearman** [comment]
@bsvensson The Sharing API supports `div` attributes `style` and `align`.

**Comment by BlakeStearman** [comment]
@bsvensson I believe it also supports `ol` and `hr` tags. I have the doc team adding those to the supported HTML doc for our next release. I can issue a PR for this change today.
