### ISSUE TITLE
Request Update on NPM & CDN

### ISSUE THREAD

**Issue by YukiDayDreamer** [Esri/arcgis-html-sanitizer#34]
Hi,

Thanks for the update of the latest release 1.0.0. I have tried to use it through `npm` package or `cdn` link but neither of them have the new white list in it. Could you please update them?

Thanks,

Yuki

**Comment by ssylvia** [comment]
Thanks for the report. I've fixed this: https://github.com/Esri/arcgis-html-sanitizer/releases/tag/v1.1.0.
