### ISSUE TITLE
Protocol problems of link tag

### ISSUE THREAD

**Issue by YukiDayDreamer** [Esri/arcgis-html-sanitizer#35]
- Strings like `<a href="mailto:user@gmail.com">Mailto</a>` and `<a href="tel:+1-111-111-1111">Tel</a>` fail the validation

- Using valid but uppercase protocols like `HTTPS` and `HTTP` will fail the validation

**Comment by ssylvia** [comment]
Fixed: https://github.com/Esri/arcgis-html-sanitizer/releases/tag/v1.2.0
