### ISSUE TITLE
Enhancement Request of URL Sanitization on Other Tags/Attributes

### ISSUE THREAD

**Issue by YukiDayDreamer** [Esri/arcgis-html-sanitizer#38]
Sanitizer will sanitize the `href` attribute in an anchor tag if it contains invalid protocol.

But for other tags in the whitelist, like: `img`, `audio`, `video` tags need the same mechanism for their `src` attribute. 

And if a user extends the whitelist with tags like `iframe`, which also may contain url in `src` and `srcdoc`, its URL will not get sanitized.

cc: @ffaubry @vijayendranj

**Comment by BlakeStearman** [comment]
@YukiDayDreamer I'm not sure I'm clear on this issue. Can you help me fill in the details?

We've extended the built-in sanitization provided by `xss` for the `a` tag `href` attribute to allow the supported ArcGIS Online protocols, such as `arcgis-navigator`, `arcgis-survery123`, etc. All other tags are passed through the built-in sanitization that `xss` provides, so attributes other than `a` `href` should be sanitized the same as before this extension.

Is this issue saying that the sanitization provided by `xss` isn't working/being called correctly for `img`, `audio`, and `video`? Or, are you asking for the supported ArcGIS Online protocols to also be allowed for `img`, `audio`, `video` as well? If the latter, are any of the supported ArcGIS Online protocols used for serving images, audio, or video, or do we have use cases requiring this? If so, I think this would be an appropriate enhancement.

**Comment by ffaubry** [comment]
@BlakeStearman Yes we saw that href is being validated for supported URL's.
Dashboard supports other tags such as img, audio, video, iframe for which we would like to apply the same rules as href for anchors.
We can have an internal discussion. This is a public repo.

**Comment by BlakeStearman** [comment]
@ffaubry Sounds good, would be happy to meet on this.

**Comment by BlakeStearman** [comment]
Sanitization of `img` `src` attribute has been addressed by PR #42. Sanitization of `audio` and `video` `src` attributes has been addressed by PR #43. The `iframe` `src` and `srcdoc` will not be addressed. Developers can extend the custom filtering options to support those cases if desired. See the [custom filtering options documentation](https://github.com/Esri/arcgis-html-sanitizer#customizing-filter-options) in the README.md.
