### ISSUE TITLE
Enhancement Request of URL Sanitization for Loopbacks

### ISSUE THREAD

**Issue by YukiDayDreamer** [Esri/arcgis-html-sanitizer#39]
In our project, we have applied filters to sanitize loopback addresses: `http://localhost`, `http://127.0.0.1`.

It would be nice to have this feature as well as the protocol validation in the URL sanitization.

cc @ffaubry @vijayendranj

**Comment by BlakeStearman** [comment]
@YukiDayDreamer Can you provide an example of what a sanitized loopback address would look like? Are you implying that `http://localhost` would sanitize to an empty string?

**Comment by ffaubry** [comment]
@BlakeStearman We are going to close this request as we (dashboard) don't need it anymore.
But, yes there is a non zero risk that url point to localhost (with all its forms of referencing) could be used for an attack.
Let's continue the discussion internally.
