### ISSUE TITLE
Enhancement Request of URL Sanitization Function

### ISSUE THREAD

**Issue by YukiDayDreamer** [Esri/arcgis-html-sanitizer#40]
Looking for an option of `sanitizeUrl` as a function, which allows us to specify customized rules for the tags/attributes need URL sanitization.

cc: @ffaubry @vijayendranj

**Comment by BlakeStearman** [comment]
A public `sanitizeUrl` method has now been made available to easily sanitize URLs according to our allowed protocols &mdash; the same rules we apply to `a` `href`, etc. This does not allow for customized rules to be passed in, however. If you want customized rules for sanitizing URL attributes, you can either override the `sanitizeUrl` method, or use custom filtering options, which are [documented in the README.md](https://github.com/Esri/arcgis-html-sanitizer#customizing-filter-options).
