### ISSUE TITLE
please add abbr tag to spec

### ISSUE THREAD

**Issue by lizeidsness** [Esri/arcgis-html-sanitizer#55]
I couldn't see where else to add to this:
https://doc.arcgis.com/en/arcgis-online/reference/supported-html.htm

Common in accessible html is the use of abbr tags to describe abbreviations.  Please consider adding these to the spec.

**Comment by bsvensson** [comment]
@BlakeStearman @ssylvia @dasa - any security concerns about `abbr`?

**Comment by dasa** [comment]
No, I think this would be good to add.

**Comment by lizeidsness** [comment]
timeline?  I've noticed in making widgets with JS API 4, abbr is not being recognized an html element from my message bundles from translations.  AFIK this library is what is sanitizing innerhtml for widgets.

**Comment by ssylvia** [comment]
This will be added in the next release of ArcGIS Online. It's also added in this library in the v2.6.0 `next` release.
