### ISSUE TITLE
The ESM build should be ES5

### ISSUE THREAD

**Issue by tomwayson** [Esri/arcgis-html-sanitizer#60]
Currently the ESM build is [distributed as ES6](https://github.com/Esri/arcgis-html-sanitizer/blob/master/rollup.config.js#L35). This breaks our app in IE.

Unfortunately, since the default behavior of bundlers like webpack is to **not** transpile dependencies, [the convention is still for libraries to distribute `package.module` as ESM w/ otherwise transpiled ES5 code](https://webpack.js.org/guides/author-libraries/#final-steps).

**Comment by dasa** [comment]
That link doesn't mention ES5, but I agree that this should be ES5 until we drop IE support.

**Comment by tomwayson** [comment]
<img width="707" alt="image" src="https://user-images.githubusercontent.com/662944/84957203-92fc6000-b0af-11ea-927c-c9b162f89034.png">

**Comment by tomwayson** [comment]
@dasa, re:

> until we drop IE support

What would you target then? ES6? How long would that be the target? To me, this is a [broader problem](https://jasonformat.com/enabling-modern-js-on-npm/) that the ecosystem doesn't have an answer for... [yet](https://twitter.com/_developit/status/1259187181219971078).

Until there's some broadly adopted convention, around how to distribute anything other than ES5, that's what I plan to ship as `module` for all my packages.

**Comment by dasa** [comment]
ES6 in this lib's code makes this lib a little smaller. I don't think it's using anything that's greater than ES6. Most of the distributed code comes from the ES5 dependencies.

Hopefully the ecosystem does get a way to flag support levels in the future.
