### ISSUE TITLE
what's so threatening about h2 tags?

### ISSUE THREAD

**Issue by tomwayson** [Esri/arcgis-html-sanitizer#8]
any reason not to include those along w/ the rest of `<h1>` - `<h6>`?

**Comment by ssylvia** [comment]
@tomwayson, Just following the spec here: https://doc.arcgis.com/en/arcgis-online/reference/supported-html.htm. Seem safe to me. You can extend the whitelist pretty easily: https://github.com/Esri/arcgis-html-sanitizer#customizing-filter-options.

**Comment by tomwayson** [comment]
Thanks @ssylvia, I did end up extending it, and yes it was easy. I just wondered if those should be added to the defaults, but I suppose there's a case for having the defaults be _just_ the ones listed in the docs.
